ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS emailed BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS digest_runs (
    run_date DATE PRIMARY KEY,
    sent_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);